FROM python:3.11-slim-bookworm

WORKDIR /app

COPY listener/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


# Create directories for static files and templates
RUN mkdir -p /app/static/js /app/templates
RUN mkdir -p /app/config

# Copy shared py_core module
COPY py_core /app/py_core

COPY listener/app ./app
COPY listener/static /app/static
COPY listener/templates /app/templates
COPY listener/config /app/config

ENV PYTHONPATH=/app

CMD ["uvicorn", "app.manager_listener_app:app", "--host", "0.0.0.0", "--port", "8000"]