from dataclasses import dataclass
from datetime import datetime
from typing import Dict, List, Optional
import logging

# Configure logging (do this once at your application startup)
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


@dataclass
class ExchangeMarketDataStats:
    name: str
    base_url: str
    candles_rate_limit: float  # requests per second
    max_candles_per_request: int
    max_historical_date: datetime
    lowest_candle_timeframe: str
    supports_1m_candle: bool
    supports_1s_candle: bool
    is_token_needed: bool
    supports_ms: bool
    mkt_endpoint: str
    mkt_example: str
    public_trades_endpoint: str
    public_trades_example: str
    orderbook_endpoint: str
    orderbook_example: str


def create_exchange_stats_dict():
    exchanges = {
        "Binance": ExchangeMarketDataStats(
            name="Binance",
            base_url="https://api.binance.com",
            candles_rate_limit=20,
            max_candles_per_request=1000,
            max_historical_date=datetime(2017, 1, 1),
            lowest_candle_timeframe="1s",
            supports_1m_candle=True,
            supports_1s_candle=True,
            is_token_needed=False,
            supports_ms=True,
            mkt_endpoint="/api/v3/klines",
            mkt_example="?symbol=BTCUSDT&interval=1m&limit=1000",
            public_trades_endpoint="/api/v3/trades",
            public_trades_example="?symbol=BTCUSDT&limit=1000",
            orderbook_endpoint="/api/v3/depth",
            orderbook_example="?symbol=BTCUSDT&limit=100",
        ),
        "OKX": ExchangeMarketDataStats(
            name="OKX",
            base_url="https://www.okx.com",
            candles_rate_limit=10,
            max_candles_per_request=300,
            max_historical_date=datetime(2017, 1, 1),
            lowest_candle_timeframe="1m",
            supports_1m_candle=True,
            supports_1s_candle=False,
            is_token_needed=False,
            supports_ms=True,
            mkt_endpoint="/api/v5/market/candles",
            mkt_example="?instId=BTC-USDT&bar=1m&limit=300",
            public_trades_endpoint="/api/v5/market/trades",
            public_trades_example="?instId=BTC-USDT&limit=100",
            orderbook_endpoint="/api/v5/market/books",
            orderbook_example="?instId=BTC-USDT&sz=100",
        ),
        "MEXC": ExchangeMarketDataStats(
            name="MEXC",
            base_url="https://api.mexc.com",
            candles_rate_limit=40,
            max_candles_per_request=1000,
            max_historical_date=datetime(2018, 1, 1),
            lowest_candle_timeframe="1m",
            supports_1m_candle=True,
            supports_1s_candle=False,
            is_token_needed=False,
            supports_ms=True,
            mkt_endpoint="/api/v3/klines",
            mkt_example="?symbol=BTCUSDT&interval=1m&limit=1000",
            public_trades_endpoint="/api/v3/trades",
            public_trades_example="?symbol=BTCUSDT&limit=1000",
            orderbook_endpoint="/api/v3/depth",
            orderbook_example="?symbol=BTCUSDT&limit=100",
        ),
        "Bitfinex": ExchangeMarketDataStats(
            name="Bitfinex",
            base_url="https://api-pub.bitfinex.com",
            candles_rate_limit=1.5,
            max_candles_per_request=10000,
            max_historical_date=datetime(2013, 1, 1),
            lowest_candle_timeframe="1m",
            supports_1m_candle=True,
            supports_1s_candle=False,
            is_token_needed=False,
            supports_ms=True,
            mkt_endpoint="/v2/candles/trade:1m:tBTCUSD/hist",
            mkt_example="?limit=10000&start=1629087660000&end=1629087720000",
            public_trades_endpoint="/v2/trades/tBTCUSD/hist",
            public_trades_example="?limit=1000&start=1629087660000&end=1629087720000",
            orderbook_endpoint="/v2/book/tBTCUSD/P0",
            orderbook_example="?len=100",
        ),
        "Bitstamp": ExchangeMarketDataStats(
            name="Bitstamp",
            base_url="https://www.bitstamp.net",
            candles_rate_limit=10,
            max_candles_per_request=1000,
            max_historical_date=datetime(2011, 1, 1),
            lowest_candle_timeframe="1m",
            supports_1m_candle=True,
            supports_1s_candle=False,
            is_token_needed=False,
            supports_ms=False,
            mkt_endpoint="/api/v2/ohlc/btcusdt/",
            mkt_example="?step=60&limit=1000",
            public_trades_endpoint="/api/v2/transactions/btcusdt/",
            public_trades_example="?time=minute&limit=1000",
            orderbook_endpoint="/api/v2/order_book/btcusdt/",
            orderbook_example="?limit=100",
        ),
        "OANDA": ExchangeMarketDataStats(
            name="OANDA",
            base_url="https://api-fxtrade.oanda.com",
            candles_rate_limit=6,
            max_candles_per_request=5000,
            max_historical_date=datetime(2000, 1, 1),
            lowest_candle_timeframe="5s",
            supports_1m_candle=True,
            supports_1s_candle=False,
            is_token_needed=True,
            supports_ms=False,
            mkt_endpoint="/v3/instruments/BTC_USD/candles",
            mkt_example="?price=M&granularity=M1&count=5000",
            public_trades_endpoint="/v3/instruments/BTC_USD/trades",
            public_trades_example="?count=500",
            orderbook_endpoint="/v3/instruments/BTC_USD/orderBook",
            orderbook_example="?time=2023-01-01T00:00:00.000000000Z",
        ),
        "Bybit": ExchangeMarketDataStats(
            name="Bybit",
            base_url="https://api.bybit.com",
            candles_rate_limit=20,
            max_candles_per_request=200,
            max_historical_date=datetime(2019, 1, 1),
            lowest_candle_timeframe="1m",
            supports_1m_candle=True,
            supports_1s_candle=False,
            is_token_needed=False,
            supports_ms=True,
            mkt_endpoint="/v5/market/kline",
            mkt_example="?category=spot&symbol=BTCUSDT&interval=1&limit=200",
            public_trades_endpoint="/v5/market/recent-trade",
            public_trades_example="?category=spot&symbol=BTCUSDT&limit=200",
            orderbook_endpoint="/v5/market/orderbook",
            orderbook_example="?category=spot&symbol=BTCUSDT&limit=100",
        ),
        "Phemex": ExchangeMarketDataStats(
            name="Phemex",
            base_url="https://api.phemex.com",
            candles_rate_limit=50,
            max_candles_per_request=1000,
            max_historical_date=datetime(2019, 1, 1),
            lowest_candle_timeframe="1m",
            supports_1m_candle=True,
            supports_1s_candle=False,
            is_token_needed=False,
            supports_ms=True,
            mkt_endpoint="/md/v3/kline",
            mkt_example="?symbol=BTCUSDT&interval=60&limit=1000",
            public_trades_endpoint="/md/v3/trade",
            public_trades_example="?symbol=BTCUSDT&limit=1000",
            orderbook_endpoint="/md/v3/orderbook",
            orderbook_example="?symbol=BTCUSDT&limit=100",
        ),
    }
    return exchanges


from typing import List


g_symbol_mapping = {
    "binanceusdm": {
        "BTCUSDT": "BTCUSDT",
        "ETHUSDT": "ETHUSDT",
        "SOLUSDT": "SOLUSDT",
        "BNBUSDT": "BNBUSDT",
        "XRPUSDT": "XRPUSDT",
        "ADAUSDT": "ADAUSDT",
        "DOGEUSDT": "DOGEUSDT",
        "TONUSDT": "TONUSDT",
        "AVAXUSDT": "AVAXUSDT",
        "SHIBUSDT": "SHIBUSDT",
        "DOTUSDT": "DOTUSDT",
        "LINKUSDT": "LINKUSDT",
        "MATICUSDT": "MATICUSDT",
        "WBTCUSDT": "WBTCUSDT",
        "UNIUSDT": "UNIUSDT",
        "LTCUSDT": "LTCUSDT",
        "BCHUSDT": "BCHUSDT",
        "ICPUSDT": "ICPUSDT",
        "FILUSDT": "FILUSDT",
        "ATOMUSDT": "ATOMUSDT",
    },
    "binance": {
        "BTCUSDT": "BTCUSDT",
        "ETHUSDT": "ETHUSDT",
        "SOLUSDT": "SOLUSDT",
        "BNBUSDT": "BNBUSDT",
        "XRPUSDT": "XRPUSDT",
        "ADAUSDT": "ADAUSDT",
        "DOGEUSDT": "DOGEUSDT",
        "TONUSDT": "TONUSDT",
        "AVAXUSDT": "AVAXUSDT",
        "SHIBUSDT": "SHIBUSDT",
        "DOTUSDT": "DOTUSDT",
        "LINKUSDT": "LINKUSDT",
        "MATICUSDT": "MATICUSDT",
        "WBTCUSDT": "WBTCUSDT",
        "UNIUSDT": "UNIUSDT",
        "LTCUSDT": "LTCUSDT",
        "BCHUSDT": "BCHUSDT",
        "ICPUSDT": "ICPUSDT",
        "FILUSDT": "FILUSDT",
        "ATOMUSDT": "ATOMUSDT",
    },
    "coinbase": {
        "BTCUSDT": "BTC-USD",
        "ETHUSDT": "ETH-USD",
        "SOLUSDT": "SOL-USD",
        "BNBUSDT": "BNB-USD",  # Note: Coinbase may not list BNB
        "XRPUSDT": "XRP-USD",
        "ADAUSDT": "ADA-USD",
        "DOGEUSDT": "DOGE-USD",
        "TONUSDT": "TON-USD",  # Verify if listed
        "AVAXUSDT": "AVAX-USD",
        "SHIBUSDT": "SHIB-USD",
        "DOTUSDT": "DOT-USD",
        "LINKUSDT": "LINK-USD",
        "MATICUSDT": "MATIC-USD",
        "WBTCUSDT": "WBTC-USD",
        "UNIUSDT": "UNI-USD",
        "LTCUSDT": "LTC-USD",
        "BCHUSDT": "BCH-USD",
        "ICPUSDT": "ICP-USD",
        "FILUSDT": "FIL-USD",
        "ATOMUSDT": "ATOM-USD",
    },
    "kraken": {
        "BTCUSDT": "XBT/USDT",  # Or "XBT/USD" for USD pairs
        "ETHUSDT": "ETH/USDT",
        "SOLUSDT": "SOL/USDT",
        "BNBUSDT": "BNB/USDT",  # Likely not listed
        "XRPUSDT": "XRP/USDT",
        "ADAUSDT": "ADA/USDT",
        "DOGEUSDT": "DOGE/USDT",
        "TONUSDT": "TON/USDT",  # Verify if listed
        "AVAXUSDT": "AVAX/USDT",
        "SHIBUSDT": "SHIB/USDT",
        "DOTUSDT": "DOT/USDT",
        "LINKUSDT": "LINK/USDT",
        "MATICUSDT": "MATIC/USDT",
        "WBTCUSDT": "WBTC/USDT",
        "UNIUSDT": "UNI/USDT",
        "LTCUSDT": "LTC/USDT",
        "BCHUSDT": "BCH/USDT",
        "ICPUSDT": "ICP/USDT",
        "FILUSDT": "FIL/USDT",
        "ATOMUSDT": "ATOM/USDT",
    },
    "bybit": {
        "BTCUSDT": "BTCUSDT",
        "ETHUSDT": "ETHUSDT",
        "SOLUSDT": "SOLUSDT",
        "BNBUSDT": "BNBUSDT",
        "XRPUSDT": "XRPUSDT",
        "ADAUSDT": "ADAUSDT",
        "DOGEUSDT": "DOGEUSDT",
        "TONUSDT": "TONUSDT",
        "AVAXUSDT": "AVAXUSDT",
        "SHIBUSDT": "SHIBUSDT",
        "DOTUSDT": "DOTUSDT",
        "LINKUSDT": "LINKUSDT",
        "MATICUSDT": "MATICUSDT",
        "WBTCUSDT": "WBTCUSDT",
        "UNIUSDT": "UNIUSDT",
        "LTCUSDT": "LTCUSDT",
        "BCHUSDT": "BCHUSDT",
        "ICPUSDT": "ICPUSDT",
        "FILUSDT": "FILUSDT",
        "ATOMUSDT": "ATOMUSDT",
    },
    "okx": {
        "BTCUSDT": "BTC-USDT",
        "ETHUSDT": "ETH-USDT",
        "SOLUSDT": "SOL-USDT",
        "BNBUSDT": "BNB-USDT",
        "XRPUSDT": "XRP-USDT",
        "ADAUSDT": "ADA-USDT",
        "DOGEUSDT": "DOGE-USDT",
        "TONUSDT": "TON-USDT",
        "AVAXUSDT": "AVAX-USDT",
        "SHIBUSDT": "SHIB-USDT",
        "DOTUSDT": "DOT-USDT",
        "LINKUSDT": "LINK-USDT",
        "MATICUSDT": "MATIC-USDT",
        "WBTCUSDT": "WBTC-USDT",
        "UNIUSDT": "UNI-USDT",
        "LTCUSDT": "LTC-USDT",
        "BCHUSDT": "BCH-USDT",
        "ICPUSDT": "ICP-USDT",
        "FILUSDT": "FIL-USDT",
        "ATOMUSDT": "ATOM-USDT",
    },
    "kucoin": {
        "BTCUSDT": "BTC-USDT",
        "ETHUSDT": "ETH-USDT",
        "SOLUSDT": "SOL-USDT",
        "BNBUSDT": "BNB-USDT",
        "XRPUSDT": "XRP-USDT",
        "ADAUSDT": "ADA-USDT",
        "DOGEUSDT": "DOGE-USDT",
        "TONUSDT": "TON-USDT",
        "AVAXUSDT": "AVAX-USDT",
        "SHIBUSDT": "SHIB-USDT",
        "DOTUSDT": "DOT-USDT",
        "LINKUSDT": "LINK-USDT",
        "MATICUSDT": "MATIC-USDT",
        "WBTCUSDT": "WBTC-USDT",
        "UNIUSDT": "UNI-USDT",
        "LTCUSDT": "LTC-USDT",
        "BCHUSDT": "BCH-USDT",
        "ICPUSDT": "ICP-USDT",
        "FILUSDT": "FIL-USDT",
        "ATOMUSDT": "ATOM-USDT",
    },
    "mexc": {
        "BTCUSDT": "BTCUSDT",
        "ETHUSDT": "ETHUSDT",
        "SOLUSDT": "SOLUSDT",
        "BNBUSDT": "BNBUSDT",
        "XRPUSDT": "XRPUSDT",
        "ADAUSDT": "ADAUSDT",
        "DOGEUSDT": "DOGEUSDT",
        "TONUSDT": "TONUSDT",
        "AVAXUSDT": "AVAXUSDT",
        "SHIBUSDT": "SHIBUSDT",
        "DOTUSDT": "DOTUSDT",
        "LINKUSDT": "LINKUSDT",
        "MATICUSDT": "MATICUSDT",
        "WBTCUSDT": "WBTCUSDT",
        "UNIUSDT": "UNIUSDT",
        "LTCUSDT": "LTCUSDT",
        "BCHUSDT": "BCHUSDT",
        "ICPUSDT": "ICPUSDT",
        "FILUSDT": "FILUSDT",
        "ATOMUSDT": "ATOMUSDT",
    },
    "gate": {"BTCUSDT": "BTC_USDT"},
    "gemini": {"BTCUSDT": "btcusd"},
    "yahoo": {
        "BTCUSDT": "BTC-USD",
        "ETHUSDT": "ETH-USD",
        "SOLUSDT": "SOL-USD",
        "BNBUSDT": "BNB-USD",
        "XRPUSDT": "XRP-USD",
        "ADAUSDT": "ADA-USD",
        "DOGEUSDT": "DOGE-USD",
        "AVAXUSDT": "AVAX-USD",
        "SHIBUSDT": "SHIB-USD",
        "DOTUSDT": "DOT-USD",
        "LINKUSDT": "LINK-USD",
        "MATICUSDT": "MATIC-USD",
        "WBTCUSDT": "WBTC-USD",
        "UNIUSDT": "UNI-USD",
        "LTCUSDT": "LTC-USD",
        "BCHUSDT": "BCH-USD",
        "ICPUSDT": "ICP-USD",
        "FILUSDT": "FIL-USD",
        "ATOMUSDT": "ATOM-USD",
        "SPYUSUSD": "SPY",
        "QQQUSUSD": "QQQ",
        "IWMUSUSD": "IWM",
    },
    "oanda": {
        "SGD_CHF": {
            "name": "SGD_CHF",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "AUD_CAD": {
            "name": "AUD_CAD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "UK10YB_GBP": {
            "name": "UK10YB_GBP",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.20,
        },
        "AU200_AUD": {
            "name": "AU200_AUD",
            "minimumTradeSize": 0.1,
            "piplocation": 0,
            "marginRate": 0.05,
        },
        "XAG_USD": {
            "name": "XAG_USD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.10,
        },
        "USD_CNH": {
            "name": "USD_CNH",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "USD_CZK": {
            "name": "USD_CZK",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "USD_HUF": {
            "name": "USD_HUF",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.05,
        },
        "EUR_CAD": {
            "name": "EUR_CAD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.03333333333333,
        },
        "XAG_CAD": {
            "name": "XAG_CAD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.10,
        },
        "XPT_USD": {
            "name": "XPT_USD",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.10,
        },
        "CHINAH_HKD": {
            "name": "CHINAH_HKD",
            "minimumTradeSize": 0.1,
            "piplocation": 0,
            "marginRate": 0.1,
        },
        "NL25_EUR": {
            "name": "NL25_EUR",
            "minimumTradeSize": 0.1,
            "piplocation": -2,
            "marginRate": 0.10,
        },
        "EUR_ZAR": {
            "name": "EUR_ZAR",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "AUD_JPY": {
            "name": "AUD_JPY",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.05,
        },
        "NZD_CHF": {
            "name": "NZD_CHF",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "AUD_SGD": {
            "name": "AUD_SGD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "AUD_HKD": {
            "name": "AUD_HKD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.1,
        },
        "WTICO_USD": {
            "name": "WTICO_USD",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.10,
        },
        "XAG_AUD": {
            "name": "XAG_AUD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.10,
        },
        "SGD_JPY": {
            "name": "SGD_JPY",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.05,
        },
        "GBP_ZAR": {
            "name": "GBP_ZAR",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "EUR_CHF": {
            "name": "EUR_CHF",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.03333333333333,
        },
        "GBP_USD": {
            "name": "GBP_USD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.03333333333333,
        },
        "USD_MXN": {
            "name": "USD_MXN",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "AUD_CHF": {
            "name": "AUD_CHF",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "XAU_HKD": {
            "name": "XAU_HKD",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.05,
        },
        "ZAR_JPY": {
            "name": "ZAR_JPY",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.05,
        },
        "CHF_ZAR": {
            "name": "CHF_ZAR",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "HKD_JPY": {
            "name": "HKD_JPY",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.1,
        },
        "SUGAR_USD": {
            "name": "SUGAR_USD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.10,
        },
        "EUR_PLN": {
            "name": "EUR_PLN",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "XAU_JPY": {
            "name": "XAU_JPY",
            "minimumTradeSize": 1,
            "piplocation": 1,
            "marginRate": 0.05,
        },
        "XCU_USD": {
            "name": "XCU_USD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.10,
        },
        "XAG_HKD": {
            "name": "XAG_HKD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.1,
        },
        "USD_HKD": {
            "name": "USD_HKD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.1,
        },
        "XAG_JPY": {
            "name": "XAG_JPY",
            "minimumTradeSize": 1,
            "piplocation": 0,
            "marginRate": 0.10,
        },
        "EUR_SGD": {
            "name": "EUR_SGD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "USD_SEK": {
            "name": "USD_SEK",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "GBP_SGD": {
            "name": "GBP_SGD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "GBP_NZD": {
            "name": "GBP_NZD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "XAU_NZD": {
            "name": "XAU_NZD",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.05,
        },
        "GBP_HKD": {
            "name": "GBP_HKD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.1,
        },
        "EUR_HKD": {
            "name": "EUR_HKD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.1,
        },
        "CHF_HKD": {
            "name": "CHF_HKD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.1,
        },
        "XAU_CHF": {
            "name": "XAU_CHF",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.05,
        },
        "USB05Y_USD": {
            "name": "USB05Y_USD",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.20,
        },
        "DE30_EUR": {
            "name": "DE30_EUR",
            "minimumTradeSize": 0.1,
            "piplocation": 0,
            "marginRate": 0.05,
        },
        "EUR_SEK": {
            "name": "EUR_SEK",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "USD_SGD": {
            "name": "USD_SGD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "TRY_JPY": {
            "name": "TRY_JPY",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.25,
        },
        "USB30Y_USD": {
            "name": "USB30Y_USD",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.20,
        },
        "USD_NOK": {
            "name": "USD_NOK",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "NZD_CAD": {
            "name": "NZD_CAD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "GBP_JPY": {
            "name": "GBP_JPY",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.03333333333333,
        },
        "USD_TRY": {
            "name": "USD_TRY",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.25,
        },
        "CN50_USD": {
            "name": "CN50_USD",
            "minimumTradeSize": 0.1,
            "piplocation": 0,
            "marginRate": 0.10,
        },
        "XAU_USD": {
            "name": "XAU_USD",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.05,
        },
        "DE10YB_EUR": {
            "name": "DE10YB_EUR",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.20,
        },
        "USB02Y_USD": {
            "name": "USB02Y_USD",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.20,
        },
        "EUR_NZD": {
            "name": "EUR_NZD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "GBP_AUD": {
            "name": "GBP_AUD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "USD_PLN": {
            "name": "USD_PLN",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "GBP_CAD": {
            "name": "GBP_CAD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.03333333333333,
        },
        "US2000_USD": {
            "name": "US2000_USD",
            "minimumTradeSize": 0.1,
            "piplocation": -2,
            "marginRate": 0.10,
        },
        "UK100_GBP": {
            "name": "UK100_GBP",
            "minimumTradeSize": 0.1,
            "piplocation": 0,
            "marginRate": 0.05,
        },
        "EUR_TRY": {
            "name": "EUR_TRY",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.25,
        },
        "USD_JPY": {
            "name": "USD_JPY",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.03333333333333,
        },
        "XAU_EUR": {
            "name": "XAU_EUR",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.05,
        },
        "USD_DKK": {
            "name": "USD_DKK",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "SPX500_USD": {
            "name": "SPX500_USD",
            "minimumTradeSize": 0.1,
            "piplocation": 0,
            "marginRate": 0.05,
        },
        "HK33_HKD": {
            "name": "HK33_HKD",
            "minimumTradeSize": 0.1,
            "piplocation": 0,
            "marginRate": 0.10,
        },
        "XAU_GBP": {
            "name": "XAU_GBP",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.05,
        },
        "EUR_GBP": {
            "name": "EUR_GBP",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.03333333333333,
        },
        "XAG_GBP": {
            "name": "XAG_GBP",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.10,
        },
        "USD_CHF": {
            "name": "USD_CHF",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.03333333333333,
        },
        "AUD_USD": {
            "name": "AUD_USD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "GBP_PLN": {
            "name": "GBP_PLN",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "EUR_JPY": {
            "name": "EUR_JPY",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.03333333333333,
        },
        "FR40_EUR": {
            "name": "FR40_EUR",
            "minimumTradeSize": 0.1,
            "piplocation": 0,
            "marginRate": 0.05,
        },
        "AUD_NZD": {
            "name": "AUD_NZD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "CHF_JPY": {
            "name": "CHF_JPY",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.03333333333333,
        },
        "CAD_CHF": {
            "name": "CAD_CHF",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.03333333333333,
        },
        "XAU_XAG": {
            "name": "XAU_XAG",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.1,
        },
        "USD_ZAR": {
            "name": "USD_ZAR",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "CAD_JPY": {
            "name": "CAD_JPY",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.03333333333333,
        },
        "XAG_SGD": {
            "name": "XAG_SGD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.10,
        },
        "XAG_NZD": {
            "name": "XAG_NZD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.10,
        },
        "US30_USD": {
            "name": "US30_USD",
            "minimumTradeSize": 0.1,
            "piplocation": 0,
            "marginRate": 0.05,
        },
        "NZD_USD": {
            "name": "NZD_USD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "XAG_CHF": {
            "name": "XAG_CHF",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.10,
        },
        "XAU_CAD": {
            "name": "XAU_CAD",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.05,
        },
        "CORN_USD": {
            "name": "CORN_USD",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.10,
        },
        "SOYBN_USD": {
            "name": "SOYBN_USD",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.10,
        },
        "EUR_DKK": {
            "name": "EUR_DKK",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.1,
        },
        "SG30_SGD": {
            "name": "SG30_SGD",
            "minimumTradeSize": 0.1,
            "piplocation": -1,
            "marginRate": 0.10,
        },
        "XAU_SGD": {
            "name": "XAU_SGD",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.05,
        },
        "GBP_CHF": {
            "name": "GBP_CHF",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.03333333333333,
        },
        "USD_THB": {
            "name": "USD_THB",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.05,
        },
        "EUR_CZK": {
            "name": "EUR_CZK",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "NZD_SGD": {
            "name": "NZD_SGD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "NATGAS_USD": {
            "name": "NATGAS_USD",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.10,
        },
        "EUR_AUD": {
            "name": "EUR_AUD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "EUR_USD": {
            "name": "EUR_USD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.03333333333333,
        },
        "WHEAT_USD": {
            "name": "WHEAT_USD",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.10,
        },
        "XAU_AUD": {
            "name": "XAU_AUD",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.05,
        },
        "USB10Y_USD": {
            "name": "USB10Y_USD",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.20,
        },
        "EU50_EUR": {
            "name": "EU50_EUR",
            "minimumTradeSize": 0.1,
            "piplocation": 0,
            "marginRate": 0.05,
        },
        "JP225Y_JPY": {
            "name": "JP225Y_JPY",
            "minimumTradeSize": 1,
            "piplocation": 0,
            "marginRate": 0.05,
        },
        "XAG_EUR": {
            "name": "XAG_EUR",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.10,
        },
        "NZD_JPY": {
            "name": "NZD_JPY",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.05,
        },
        "NAS100_USD": {
            "name": "NAS100_USD",
            "minimumTradeSize": 0.1,
            "piplocation": 0,
            "marginRate": 0.05,
        },
        "EUR_NOK": {
            "name": "EUR_NOK",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "CAD_SGD": {
            "name": "CAD_SGD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.05,
        },
        "XPD_USD": {
            "name": "XPD_USD",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.10,
        },
        "USD_CAD": {
            "name": "USD_CAD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.03333333333333,
        },
        "EUR_HUF": {
            "name": "EUR_HUF",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.05,
        },
        "JP225_USD": {
            "name": "JP225_USD",
            "minimumTradeSize": 0.1,
            "piplocation": 0,
            "marginRate": 0.05,
        },
        "BCO_USD": {
            "name": "BCO_USD",
            "minimumTradeSize": 1,
            "piplocation": -2,
            "marginRate": 0.10,
        },
        "CAD_HKD": {
            "name": "CAD_HKD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.1,
        },
        "CH20_CHF": {
            "name": "CH20_CHF",
            "minimumTradeSize": 0.1,
            "piplocation": 0,
            "marginRate": 0.1,
        },
        "NZD_HKD": {
            "name": "NZD_HKD",
            "minimumTradeSize": 1,
            "piplocation": -4,
            "marginRate": 0.1,
        },
        "ESPIX_EUR": {
            "name": "ESPIX_EUR",
            "minimumTradeSize": 0.1,
            "piplocation": 0,
            "marginRate": 0.1,
        },
    },
    "sp500": {
        "A": "A",
        "AAP": "AAP",
        "AAPL": "AAPL",
        "ABBV": "ABBV",
        "ABC": "ABC",
        "ABMD": "ABMD",
        "ABT": "ABT",
        "ACGL": "ACGL",
        "ACN": "ACN",
        "ADBE": "ADBE",
        "ADI": "ADI",
        "ADM": "ADM",
        "ADSK": "ADSK",
        "AEE": "AEE",
        "AEP": "AEP",
        "AES": "AES",
        "AFL": "AFL",
        "AIG": "AIG",
        "AIZ": "AIZ",
        "AJG": "AJG",
        "AKAM": "AKAM",
        "ALB": "ALB",
        "ALGN": "ALGN",
        "ALK": "ALK",
        "ALL": "ALL",
        "ALLE": "ALLE",
        "AMAT": "AMAT",
        "AMCR": "AMCR",
        "AME": "AME",
        "AMGN": "AMGN",
        "AMP": "AMP",
        "AMT": "AMT",
        "AMZN": "AMZN",
        "ANET": "ANET",
        "ANSS": "ANSS",
        "AON": "AON",
        "AOS": "AOS",
        "APA": "APA",
        "APD": "APD",
        "APH": "APH",
        "APTV": "APTV",
        "ARE": "ARE",
        "ATO": "ATO",
        "ATVI": "ATVI",
        "AVB": "AVB",
        "AVGO": "AVGO",
        "AVY": "AVY",
        "AWK": "AWK",
        "AXP": "AXP",
        "AZO": "AZO",
        "BA": "BA",
        "BAC": "BAC",
        "BALL": "BALL",
        "BAX": "BAX",
        "BBWI": "BBWI",
        "BBY": "BBY",
        "BDX": "BDX",
        "BEN": "BEN",
        "BF-B": "BF-B",
        "BG": "BG",
        "BIIB": "BIIB",
        "BIO": "BIO",
        "BK": "BK",
        "BKNG": "BKNG",
        "BKR": "BKR",
        "BLK": "BLK",
        "BMY": "BMY",
        "BR": "BR",
        "BRK-B": "BRK-B",
        "BRO": "BRO",
        "BSX": "BSX",
        "BWA": "BWA",
        "BXP": "BXP",
        "C": "C",
        "CAG": "CAG",
        "CAH": "CAH",
        "CARR": "CARR",
        "CAT": "CAT",
        "CB": "CB",
        "CBOE": "CBOE",
        "CBRE": "CBRE",
        "CCI": "CCI",
        "CCL": "CCL",
        "CDAY": "CDAY",
        "CDNS": "CDNS",
        "CDW": "CDW",
        "CE": "CE",
        "CEG": "CEG",
        "CF": "CF",
        "CFG": "CFG",
        "CHD": "CHD",
        "CHRW": "CHRW",
        "CHTR": "CHTR",
        "CI": "CI",
        "CINF": "CINF",
        "CL": "CL",
        "CLX": "CLX",
        "CMA": "CMA",
        "CMCSA": "CMCSA",
        "CME": "CME",
        "CMG": "CMG",
        "CMI": "CMI",
        "CMS": "CMS",
        "CNC": "CNC",
        "CNP": "CNP",
        "COF": "COF",
        "COO": "COO",
        "COP": "COP",
        "COST": "COST",
        "CPB": "CPB",
        "CPRT": "CPRT",
        "CRL": "CRL",
        "CRM": "CRM",
        "CSCO": "CSCO",
        "CSGP": "CSGP",
        "CSX": "CSX",
        "CTAS": "CTAS",
        "CTRA": "CTRA",
        "CTSH": "CTSH",
        "CTVA": "CTVA",
        "CTXS": "CTXS",
        "CVS": "CVS",
        "CVX": "CVX",
        "CZR": "CZR",
        "D": "D",
        "DAL": "DAL",
        "DD": "DD",
        "DE": "DE",
        "DFS": "DFS",
        "DG": "DG",
        "DGX": "DGX",
        "DHI": "DHI",
        "DHR": "DHR",
        "DIS": "DIS",
        "DLR": "DLR",
        "DLTR": "DLTR",
        "DOV": "DOV",
        "DOW": "DOW",
        "DPZ": "DPZ",
        "DRE": "DRE",
        "DRI": "DRI",
        "DTE": "DTE",
        "DUK": "DUK",
        "DVA": "DVA",
        "DXC": "DXC",
        "DXCM": "DXCM",
        "EA": "EA",
        "EBAY": "EBAY",
        "ECL": "ECL",
        "ED": "ED",
        "EFX": "EFX",
        "EIX": "EIX",
        "EL": "EL",
        "EMN": "EMN",
        "EMR": "EMR",
        "ENPH": "ENPH",
        "EOG": "EOG",
        "EPAM": "EPAM",
        "EQIX": "EQIX",
        "EQR": "EQR",
        "EQT": "EQT",
        "ES": "ES",
        "ESS": "ESS",
        "ETN": "ETN",
        "ETR": "ETR",
        "ETSY": "ETSY",
        "EVRG": "EVRG",
        "EW": "EW",
        "EXC": "EXC",
        "EXPD": "EXPD",
        "EXPE": "EXPE",
        "EXR": "EXR",
        "F": "F",
        "FANG": "FANG",
        "FAST": "FAST",
        "FCX": "FCX",
        "FDS": "FDS",
        "FDX": "FDX",
        "FE": "FE",
        "FFIV": "FFIV",
        "FIS": "FIS",
        "FISV": "FISV",
        "FLT": "FLT",
        "FMC": "FMC",
        "FOX": "FOX",
        "FOXA": "FOXA",
        "FRT": "FRT",
        "FSLR": "FSLR",
        "FTNT": "FTNT",
        "FTV": "FTV",
        "GD": "GD",
        "GE": "GE",
        "GEHC": "GEHC",
        "GEN": "GEN",
        "GILD": "GILD",
        "GIS": "GIS",
        "GL": "GL",
        "GLW": "GLW",
        "GM": "GM",
        "GNRC": "GNRC",
        "GOOG": "GOOG",
        "GOOGL": "GOOGL",
        "GPC": "GPC",
        "GPN": "GPN",
        "GRMN": "GRMN",
        "GS": "GS",
        "GWW": "GWW",
        "HAL": "HAL",
        "HAS": "HAS",
        "HBAN": "HBAN",
        "HCA": "HCA",
        "HD": "HD",
        "HES": "HES",
        "HIG": "HIG",
        "HII": "HII",
        "HLT": "HLT",
        "HOLX": "HOLX",
        "HON": "HON",
        "HPE": "HPE",
        "HPQ": "HPQ",
        "HRL": "HRL",
        "HSIC": "HSIC",
        "HST": "HST",
        "HSY": "HSY",
        "HUM": "HUM",
        "HWM": "HWM",
        "IBM": "IBM",
        "ICE": "ICE",
        "IDXX": "IDXX",
        "IEX": "IEX",
        "IFF": "IFF",
        "ILMN": "ILMN",
        "INCY": "INCY",
        "INTC": "INTC",
        "INTU": "INTU",
        "INVH": "INVH",
        "IP": "IP",
        "IPG": "IPG",
        "IQV": "IQV",
        "IR": "IR",
        "IRM": "IRM",
        "ISRG": "ISRG",
        "IT": "IT",
        "ITW": "ITW",
        "IVZ": "IVZ",
        "J": "J",
        "JBHT": "JBHT",
        "JCI": "JCI",
        "JKHY": "JKHY",
        "JNJ": "JNJ",
        "JNPR": "JNPR",
        "JPM": "JPM",
        "K": "K",
        "KDP": "KDP",
        "KEY": "KEY",
        "KEYS": "KEYS",
        "KHC": "KHC",
        "KIM": "KIM",
        "KLAC": "KLAC",
        "KMB": "KMB",
        "KMI": "KMI",
        "KMX": "KMX",
        "KO": "KO",
        "KR": "KR",
        "LH": "LH",
        "LHX": "LHX",
        "LIN": "LIN",
        "LKQ": "LKQ",
        "LMT": "LMT",
        "LNT": "LNT",
        "LOW": "LOW",
        "LRCX": "LRCX",
        "LUV": "LUV",
        "LW": "LW",
        "LYB": "LYB",
        "LYV": "LYV",
        "MA": "MA",
        "MAA": "MAA",
        "MAR": "MAR",
        "MAS": "MAS",
        "MCD": "MCD",
        "MCHP": "MCHP",
        "MCK": "MCK",
        "MCO": "MCO",
        "MDLZ": "MDLZ",
        "MDT": "MDT",
        "MET": "MET",
        "MGM": "MGM",
        "MHK": "MHK",
        "MKC": "MKC",
        "MKTX": "MKTX",
        "MLM": "MLM",
        "MMC": "MMC",
        "MMM": "MMM",
        "MNST": "MNST",
        "MO": "MO",
        "MOS": "MOS",
        "MPC": "MPC",
        "MPWR": "MPWR",
        "MRK": "MRK",
        "MRNA": "MRNA",
        "MRO": "MRO",
        "MS": "MS",
        "MSCI": "MSCI",
        "MSFT": "MSFT",
        "MSI": "MSI",
        "MTB": "MTB",
        "MTCH": "MTCH",
        "MTD": "MTD",
        "MU": "MU",
        "NCLH": "NCLH",
        "NDAQ": "NDAQ",
        "NDSN": "NDSN",
        "NEE": "NEE",
        "NEM": "NEM",
        "NFLX": "NFLX",
        "NI": "NI",
        "NKE": "NKE",
        "NOC": "NOC",
        "NOW": "NOW",
        "NRG": "NRG",
        "NSC": "NSC",
        "NTAP": "NTAP",
        "NTRS": "NTRS",
        "NUE": "NUE",
        "NVDA": "NVDA",
        "NVR": "NVR",
        "NWS": "NWS",
        "NWSA": "NWSA",
        "NXPI": "NXPI",
        "O": "O",
        "ODFL": "ODFL",
        "OGN": "OGN",
        "OKE": "OKE",
        "OMC": "OMC",
        "ON": "ON",
        "ORCL": "ORCL",
        "ORLY": "ORLY",
        "OTIS": "OTIS",
        "OXY": "OXY",
        "PARA": "PARA",
        "PAYC": "PAYC",
        "PAYX": "PAYX",
        "PCAR": "PCAR",
        "PEAK": "PEAK",
        "PEG": "PEG",
        "PEP": "PEP",
        "PFE": "PFE",
        "PFG": "PFG",
        "PG": "PG",
        "PGR": "PGR",
        "PH": "PH",
        "PHM": "PHM",
        "PKG": "PKG",
        "PKI": "PKI",
        "PLD": "PLD",
        "PM": "PM",
        "PNC": "PNC",
        "PNR": "PNR",
        "PNW": "PNW",
        "POOL": "POOL",
        "PPG": "PPG",
        "PPL": "PPL",
        "PRU": "PRU",
        "PSA": "PSA",
        "PSX": "PSX",
        "PTC": "PTC",
        "PWR": "PWR",
        "PXD": "PXD",
        "QCOM": "QCOM",
        "QRVO": "QRVO",
        "RCL": "RCL",
        "REG": "REG",
        "REGN": "REGN",
        "RF": "RF",
        "RHI": "RHI",
        "RJF": "RJF",
        "RL": "RL",
        "RMD": "RMD",
        "ROK": "ROK",
        "ROL": "ROL",
        "ROP": "ROP",
        "ROST": "ROST",
        "RSG": "RSG",
        "RTX": "RTX",
        "SBAC": "SBAC",
        "SBUX": "SBUX",
        "SCHW": "SCHW",
        "SEE": "SEE",
        "SHW": "SHW",
        "SIVB": "SIVB",
        "SJM": "SJM",
        "SLB": "SLB",
        "SNA": "SNA",
        "SNPS": "SNPS",
        "SO": "SO",
        "SPG": "SPG",
        "SPGI": "SPGI",
        "SRE": "SRE",
        "STE": "STE",
        "STT": "STT",
        "STX": "STX",
        "STZ": "STZ",
        "SWK": "SWK",
        "SWKS": "SWKS",
        "SYF": "SYF",
        "SYK": "SYK",
        "SYY": "SYY",
        "T": "T",
        "TAP": "TAP",
        "TDG": "TDG",
        "TDY": "TDY",
        "TEL": "TEL",
        "TER": "TER",
        "TFC": "TFC",
        "TFX": "TFX",
        "TGT": "TGT",
        "TJX": "TJX",
        "TMO": "TMO",
        "TMUS": "TMUS",
        "TPR": "TPR",
        "TRGP": "TRGP",
        "TRMB": "TRMB",
        "TROW": "TROW",
        "TRV": "TRV",
        "TSCO": "TSCO",
        "TSLA": "TSLA",
        "TSN": "TSN",
        "TT": "TT",
        "TTWO": "TTWO",
        "TXN": "TXN",
        "TXT": "TXT",
        "TYL": "TYL",
        "UAL": "UAL",
        "UDR": "UDR",
        "UHS": "UHS",
        "ULTA": "ULTA",
        "UNH": "UNH",
        "UNM": "UNM",
        "UNP": "UNP",
        "UPS": "UPS",
        "URI": "URI",
        "USB": "USB",
        "V": "V",
        "VFC": "VFC",
        "VICI": "VICI",
        "VLO": "VLO",
        "VRSK": "VRSK",
        "VRSN": "VRSN",
        "VRTX": "VRTX",
        "VTR": "VTR",
        "VZ": "VZ",
        "WAB": "WAB",
        "WAT": "WAT",
        "WBA": "WBA",
        "WDC": "WDC",
        "WEC": "WEC",
        "WELL": "WELL",
        "WFC": "WFC",
        "WHR": "WHR",
        "WM": "WM",
        "WMB": "WMB",
        "WMT": "WMT",
        "WRB": "WRB",
        "WRK": "WRK",
        "WST": "WST",
        "WTW": "WTW",
        "WU": "WU",
        "WY": "WY",
        "WYNN": "WYNN",
        "XEL": "XEL",
        "XLNX": "XLNX",
        "XOM": "XOM",
        "XRAY": "XRAY",
        "XYL": "XYL",
        "YUM": "YUM",
        "ZBH": "ZBH",
        "ZBRA": "ZBRA",
        "ZION": "ZION",
        "ZTS": "ZTS",
    },
    "nasdaq100": {
        "AAPL": "AAPL",
        "ADBE": "ADBE",
        "ADI": "ADI",
        "ADP": "ADP",
        "ADSK": "ADSK",
        "AFRM": "AFRM",
        "AMD": "AMD",
        "AMGN": "AMGN",
        "AMZN": "AMZN",
        "ANSS": "ANSS",
        "ASML": "ASML",
        "ATVI": "ATVI",
        "AVGO": "AVGO",
        "BABA": "BABA",
        "BIDU": "BIDU",
        "BIIB": "BIIB",
        "BILI": "BILI",
        "BILL": "BILL",
        "BKNG": "BKNG",
        "CDNS": "CDNS",
        "CHTR": "CHTR",
        "CHWY": "CHWY",
        "CMCSA": "CMCSA",
        "CNI": "CNI",
        "COIN": "COIN",
        "COST": "COST",
        "CRWD": "CRWD",
        "CSCO": "CSCO",
        "CSX": "CSX",
        "CTAS": "CTAS",
        "CTSH": "CTSH",
        "CZR": "CZR",
        "DDOG": "DDOG",
        "DOCU": "DOCU",
        "DOYU": "DOYU",
        "DXCM": "DXCM",
        "EA": "EA",
        "ETSY": "ETSY",
        "EXC": "EXC",
        "FAST": "FAST",
        "FISV": "FISV",
        "FIVN": "FIVN",
        "GILD": "GILD",
        "GOOG": "GOOG",
        "GOOGL": "GOOGL",
        "HOOD": "HOOD",
        "HUBS": "HUBS",
        "HUYA": "HUYA",
        "ICLR": "ICLR",
        "IDXX": "IDXX",
        "INTC": "INTC",
        "INTU": "INTU",
        "IQ": "IQ",
        "ISRG": "ISRG",
        "JD": "JD",
        "KDP": "KDP",
        "KE Holdings": "KE Holdings",
        "KLAC": "KLAC",
        "LCID": "LCID",
        "LI": "LI",
        "LRCX": "LRCX",
        "LULU": "LULU",
        "MDLZ": "MDLZ",
        "MEITUAN": "MEITUAN",
        "MELI": "MELI",
        "META": "META",
        "MNST": "MNST",
        "MRNA": "MRNA",
        "MRVL": "MRVL",
        "MSFT": "MSFT",
        "MU": "MU",
        "NETEASE": "NETEASE",
        "NFLX": "NFLX",
        "NIO": "NIO",
        "NTAP": "NTAP",
        "NTES": "NTES",
        "NVDA": "NVDA",
        "NXPI": "NXPI",
        "ODFL": "ODFL",
        "OKTA": "OKTA",
        "PATH": "PATH",
        "PDD": "PDD",
        "PEP": "PEP",
        "PLTR": "PLTR",
        "PTON": "PTON",
        "PYPL": "PYPL",
        "QCOM": "QCOM",
        "RBLX": "RBLX",
        "REGN": "REGN",
        "RIVN": "RIVN",
        "ROP": "ROP",
        "ROST": "ROST",
        "SBUX": "SBUX",
        "SNOW": "SNOW",
        "SNPS": "SNPS",
        "SOFI": "SOFI",
        "SPLK": "SPLK",
        "SQ": "SQ",
        "TEAM": "TEAM",
        "TME": "TME",
        "TMUS": "TMUS",
        "TSLA": "TSLA",
        "TWLO": "TWLO",
        "TXN": "TXN",
        "UPST": "UPST",
        "VIPS": "VIPS",
        "VRSK": "VRSK",
        "VRTX": "VRTX",
        "WBA": "WBA",
        "WBD": "WBD",
        "WD": "WD",
        "WDAY": "WDAY",
        "XEL": "XEL",
        "XPENG": "XPENG",
        "XPEV": "XPEV",
        "ZI": "ZI",
        "ZM": "ZM",
        "ZS": "ZS",
    },
}


def get_mapped_symbol(exchange_name: str, symbol: str) -> str:
    """
    Get the exchange-specific symbol using the mapping.

    Args:
        exchange_name: Name of the exchange (e.g., 'binanceusdm', 'oanda')
        symbol: The symbol to look up (e.g., 'BTCUSDT')

    Returns:
        The mapped symbol for the specific exchange

    Raises:
        ValueError: If exchange or symbol is not found in the mapping
    """
    # Log the attempt to map the symbol
    logger.debug(f"Attempting to map symbol {symbol} for exchange {exchange_name}")

    # Get exchange map
    exchange_map = g_symbol_mapping.get(exchange_name)
    if not exchange_map:
        error_msg = f"Exchange '{exchange_name}' not found in symbol mapping. Available exchanges: {list(g_symbol_mapping.keys())}"
        logger.error(error_msg)
        raise ValueError(error_msg)

    try:
        # Special handling for OANDA
        if exchange_name == "oanda":
            symbol_info = exchange_map.get(symbol)
            if not symbol_info:
                error_msg = f"Symbol '{symbol}' not found for exchange {exchange_name}. Available symbols: {list(exchange_map.keys())}"
                logger.error(error_msg)
                raise ValueError(error_msg)

            mapped_symbol = symbol_info.get("name")
            if not mapped_symbol:
                error_msg = f"OANDA symbol '{symbol}' missing 'name' field in mapping"
                logger.error(error_msg)
                raise ValueError(error_msg)
        else:
            # Standard handling for other exchanges
            mapped_symbol = exchange_map.get(symbol)
            if not mapped_symbol:
                error_msg = f"Symbol '{symbol}' not found for exchange {exchange_name}. Available symbols: {list(exchange_map.keys())}"
                logger.error(error_msg)
                raise ValueError(error_msg)

        logger.debug(
            f"Successfully mapped {symbol} to {mapped_symbol} for {exchange_name}"
        )
        return mapped_symbol

    except Exception as e:
        error_msg = (
            f"Unexpected error mapping symbol {symbol} for {exchange_name}: {str(e)}"
        )
        logger.exception(error_msg)  # This will log the full traceback
        raise ValueError(error_msg) from e
