services:
  listener_prod_binance_usdm_ws:
    build:
      context: ..
      dockerfile: dockerfile_list
    ports:
      - "8012:8000"
    env_file:
      - ../../.env.prod
    environment:
      - REDIS_HOST=redis
      - LISTENER_ID=listener_prod_binance_usdm_ws
      - SYSTEM_NAME=listener
      - SERVICE_NAME=listener_prod_binance_usdm_ws
      - SERVICE_ID=listener_prod_binance_usdm_ws-id
      - SERVICE_PATH=listener_ui
      - DOCKER_URL=http://listener_prod_binance_usdm_ws:8000/
      - EXTERNAL_URL=http://192.168.0.101:8012/
      - REGISTRATION_TOKEN=${REGISTRATION_TOKEN}
      - PORTAL_URL=http://portal:8000
    volumes:
      - ../config:/app/config
    restart: unless-stopped
    networks:
      - net_redis_6477
      - web_list
      - portal-network
volumes:
  redis_data:
  
networks:
  net_redis_6477:
    external: true
    name: net_redis_6477
    driver: bridge
  web_list:
    driver: bridge
  portal-network:
    name: portal-network
    external: true